### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by nataliia-sydorenko** [nataliia-sydorenko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by volodymyr-kushnir** [comment]
@nataliia-sydorenko хей! привіт! ти хочеш, щоб я накопіпастив тобі сюди чи накопіпастиш сама? **Assignee** на мене, тому я і питаю 😊

**Comment by nataliia-sydorenko** [comment]
@volodymyr-kushnir Привiт! Дякую за допомогу, накопiпащу сама. 😊
